name: Deploy serverless app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Update with your python version

      - name: Serverless Deploy
        uses: dhollerbach/actions.serverless-with-python-requirements@master
        with:
          args: "" # any deploy arguments you want to pass
        env:
          SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
          SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          DECISIONS_S3_BUCKET: ${{ secrets.DECISIONS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
